repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--safe]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        exclude: '^tests/.*$'
        additional_dependencies: ['flake8-coding==1.3.2']
    -   id: flake8
        name: flake8-tests
        files: '^tests/.*$'
        additional_dependencies: ['flake8-pytest-style==1.6.0']