name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        # python-version: [3.7, 3.8, 3.9, "3.10", 'pypy-3.7']
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
    - name: Archive LITF files
      uses: actions/upload-artifact@v3
      with:
        name: LITF outputs
        path: |
          litf/*.litf
    - name: Test Summary
      uses: lothiraldan/test-summary-action@47e8504f69a55bf2545003cc717b94472ca76e12
      with:
        paths: "litf/*.litf"
      if: always()