name: package

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Build pip package
              run: |
                  pip install -U pip wheel
                  python setup.py sdist bdist_wheel
            - name: Archive Pypi artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: pypi_dist
                  path: dist
