name: Test Summary

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/litf-job-summary
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}